// app/src/modules/Header/Header.svelte
<script lang="ts">
	import Logo from 'src/svg/Logo.svelte';
	import Github from 'src/svg/Github.svelte';
	import Twitter from 'src/svg/Twitter.svelte';
	import Facebook from 'src/svg/Facebook.svelte';
</script>

<header>
	<div class="logo">
		<Logo />
	</div>

	<div class="socials">
		<button class="share share--facebook">
			<span class="icon--small">
				<Facebook />
			</span>
			<p>Share on Facebook</p>
		</button>

		<button class="share share--twitter">
			<span class="icon--small">
				<Twitter />
			</span>
			<p>Share on Twitter</p>
		</button>

		<div class="icon">
			<Github />
		</div>
	</div>
</header>

<style lang="scss">
	header {
		display: flex;
		justify-content: space-between;
		align-items: center;
		height: 54px;
		padding: 0 24px;
		margin: auto;
		/* border-bottom: solid 1px blue; */
	}

	.logo {
		width: 100px;
	}

	.icon {
		width: 24px;

		&--small {
			width: 12px;
		}
	}

	.socials {
		gap: 8px;
		display: flex;
		align-items: center;
		justify-content: center;
	}

	.share {
		all: unset;
		gap: 6px;
		display: flex;
		align-items: center;
		justify-content: center;
		padding: 2px 12px;
		border-radius: 4px;
		height: 24px;
		cursor: pointer;
		color: white;
		transition: transform 100ms ease-out;
		will-change: transform;

		&:hover {
			opacity: 0.8;
		}

		&:active {
			transform: scale(0.95);
		}

		&--facebook {
			background-color: #1877f2;
		}

		&--twitter {
			background-color: #1da1f2;
		}

		p {
			margin: 0;
			padding: 0;
			font-size: 12px;
			font-weight: 500;
			margin-top: 2px;
		}
	}
</style>

// web/core/Header/index.tsx
import React from 'react'
import styled, { css } from 'styled-components'

import Container from '../Container'

import Stack from '../../components/Stack'

import RawLogo from './icons/logo.svg'
import FB from './icons/facebook.svg'
import TW from './icons/twitter.svg'

const Logo = styled(RawLogo)`
  color: black;
  width: 114px;
  height: 26px;
`

const Wrapper = styled(Container)`
  display: flex;
  justify-content: space-between;
`

interface SocialProps {
  facebook?: boolean,
  twitter?: boolean,
}

const Social = styled.div<SocialProps>`
  border: 0;
  border-radius: 4px;
  color: #fff;
  font-weight: 600;
  padding: 0 8px 0 8px;
  background-color: #eaeaea;
  text-decoration: none;
  height: 30px;
  line-height: 30px;
  font-size: 13px;
  width: 140px;
  outline: 0;
  transition: background-color 0.2s ease-in-out;
  fill: white;
  display: flex;
  align-items: center;
  justify-content: center;

  svg {
    width: 16px;
    height: 16px;
    margin-right: 4px;
  }

  ${props => props.facebook && css`
    background-color: #3b5998;
    &:hover {
      background-color: darken(#3b5998, 5%);
    }
  `}

  ${props => props.twitter && css`
    background-color: #1da1f2;
    &:hover {
      background-color: darken(#1da1f2, 5%);
    }
  `}
`

const Header: React.FC = () => {
  return (
    <Wrapper as="header">
      <section>
        <Logo />
      </section>
      <section>

        <Stack gap={2}>
          <Social facebook={true}>
            <FB />
            <span>Facebook</span>
          </Social>

          <Social twitter={true}>
            <TW />
            <span>Twitter</span>
          </Social>
        </Stack>
      </section>
    </Wrapper>
  )
}

export default Header
