// app/src/modules/Actionbar/Actionbar.svelte
<section class="wrapper flex">
	<p>menu</p>
	<p>favs</p>
</section>

<style lang="scss">
	.wrapper {
		margin: auto;
		grid-area: actionbar;
		width: calc(100vw - var(--sitePadding));
		height: 100%;
		justify-content: space-between;
	}

	p {
		font-size: 14px;
	}

	.flex {
		display: flex;
		align-items: top;
	}
</style>

// web/components/core/Actionbar/index.tsx
import React from 'react'
import styled from 'styled-components'

import Container from '../Container'

import Controls from './Controls'
import Swatches from './Swatches'
import Actions from './Actions'

const Bar = styled(Container)`
  height: ${p => p.theme.heights.actionbar};
  display: flex;
  justify-content: space-between;
  align-items: baseline;
`

const Actionbar = () => {
  return (
    <Bar as="section">
      <Controls />
      <Swatches />
      <Actions />
    </Bar>
  )
}

export default Actionbar
